# Generated by Django 6.0 on 2026-05-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Type',
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Type'},
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_categor_4fa2e6_idx',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='category',
            new_name='type',
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['type'], name='places_plac_type_id_bcf671_idx'),
        ),
    ]
