# Generated by Django 6.0 on 2026-03-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/Avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
