# Generated by Django 6.0 on 2026-04-03 16:30

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='school',
            name='unique_clean_school_name',
        ),
        migrations.AddField(
            model_name='school',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated normalized version for uniqueness', max_length=250),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='School Name'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('normalized_name')), name='unique_clean_school_name'),
        ),
    ]
