# Generated by Django 6.0 on 2026-04-03 16:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle', '0002_remove_school_unique_clean_school_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='school',
            name='unique_clean_school_name',
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(default='test', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='test', max_length=250, null=True),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_clean_school_name'),
        ),
        migrations.RemoveField(
            model_name='school',
            name='normalized_name',
        ),
    ]
