# Generated by Django 6.0 on 2026-04-01 17:57

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle', '0002_alter_hospital_address_alter_hospital_facility_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hospital',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('facility')), name='unique_clean_hospital_facility'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_clean_library_name'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_clean_school_name'),
        ),
    ]
